# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BoardUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BoardUI(object):
    def setupUi(self, BoardUI):
        BoardUI.setObjectName("BoardUI")
        BoardUI.resize(415, 182)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        BoardUI.setFont(font)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(BoardUI)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lbl_CurrentCost = QtWidgets.QLabel(BoardUI)
        self.lbl_CurrentCost.setObjectName("lbl_CurrentCost")
        self.horizontalLayout.addWidget(self.lbl_CurrentCost)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.lbl_TotalCost = QtWidgets.QLabel(BoardUI)
        self.lbl_TotalCost.setObjectName("lbl_TotalCost")
        self.horizontalLayout.addWidget(self.lbl_TotalCost)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pbt_ChangeBoard = QtWidgets.QPushButton(BoardUI)
        self.pbt_ChangeBoard.setMinimumSize(QtCore.QSize(80, 30))
        self.pbt_ChangeBoard.setObjectName("pbt_ChangeBoard")
        self.horizontalLayout.addWidget(self.pbt_ChangeBoard)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.pbt_SolveGame = QtWidgets.QPushButton(BoardUI)
        self.pbt_SolveGame.setMinimumSize(QtCore.QSize(80, 30))
        self.pbt_SolveGame.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pbt_SolveGame.setObjectName("pbt_SolveGame")
        self.horizontalLayout.addWidget(self.pbt_SolveGame)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.tbw_Board = QtWidgets.QTableWidget(BoardUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbw_Board.sizePolicy().hasHeightForWidth())
        self.tbw_Board.setSizePolicy(sizePolicy)
        self.tbw_Board.setMinimumSize(QtCore.QSize(0, 0))
        self.tbw_Board.setObjectName("tbw_Board")
        self.tbw_Board.setColumnCount(0)
        self.tbw_Board.setRowCount(0)
        self.horizontalLayout_2.addWidget(self.tbw_Board)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.lbl_Info = QtWidgets.QLabel(BoardUI)
        self.lbl_Info.setObjectName("lbl_Info")
        self.verticalLayout.addWidget(self.lbl_Info)
        self.horizontalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(BoardUI)
        self.pbt_SolveGame.clicked.connect(BoardUI.slot_pbt_SolveGame_clicked)
        self.pbt_ChangeBoard.clicked.connect(BoardUI.slot_pbt_ChangeBoard_clicked)
        QtCore.QMetaObject.connectSlotsByName(BoardUI)

    def retranslateUi(self, BoardUI):
        _translate = QtCore.QCoreApplication.translate
        BoardUI.setWindowTitle(_translate("BoardUI", "LinkLink"))
        self.lbl_CurrentCost.setText(_translate("BoardUI", "当前代价：0"))
        self.lbl_TotalCost.setText(_translate("BoardUI", "总代价：0"))
        self.pbt_ChangeBoard.setText(_translate("BoardUI", "换一个"))
        self.pbt_SolveGame.setText(_translate("BoardUI", "求解"))
        self.lbl_Info.setText(_translate("BoardUI", "Info..."))
