# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InitBoardUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InitBoardUI(object):
    def setupUi(self, InitBoardUI):
        InitBoardUI.setObjectName("InitBoardUI")
        InitBoardUI.resize(545, 561)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        InitBoardUI.setFont(font)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(InitBoardUI)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.line_2 = QtWidgets.QFrame(InitBoardUI)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.lbl_Img1 = ImgLabel(InitBoardUI)
        self.lbl_Img1.setMinimumSize(QtCore.QSize(50, 50))
        self.lbl_Img1.setMaximumSize(QtCore.QSize(50, 50))
        self.lbl_Img1.setText("")
        self.lbl_Img1.setObjectName("lbl_Img1")
        self.horizontalLayout.addWidget(self.lbl_Img1)
        self.line = QtWidgets.QFrame(InitBoardUI)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.lbl_Img2 = ImgLabel(InitBoardUI)
        self.lbl_Img2.setMinimumSize(QtCore.QSize(50, 50))
        self.lbl_Img2.setMaximumSize(QtCore.QSize(50, 50))
        self.lbl_Img2.setText("")
        self.lbl_Img2.setObjectName("lbl_Img2")
        self.horizontalLayout.addWidget(self.lbl_Img2)
        self.line_3 = QtWidgets.QFrame(InitBoardUI)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pbt_Sure = QtWidgets.QPushButton(InitBoardUI)
        self.pbt_Sure.setObjectName("pbt_Sure")
        self.horizontalLayout.addWidget(self.pbt_Sure)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tbw_Board = QtWidgets.QTableWidget(InitBoardUI)
        self.tbw_Board.setObjectName("tbw_Board")
        self.tbw_Board.setColumnCount(0)
        self.tbw_Board.setRowCount(0)
        self.verticalLayout.addWidget(self.tbw_Board)
        self.lbl_Info = QtWidgets.QLabel(InitBoardUI)
        self.lbl_Info.setObjectName("lbl_Info")
        self.verticalLayout.addWidget(self.lbl_Info)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(InitBoardUI)
        self.pbt_Sure.clicked.connect(InitBoardUI.slot_pbt_Sure_clicked)
        QtCore.QMetaObject.connectSlotsByName(InitBoardUI)

    def retranslateUi(self, InitBoardUI):
        _translate = QtCore.QCoreApplication.translate
        InitBoardUI.setWindowTitle(_translate("InitBoardUI", "Form"))
        self.pbt_Sure.setText(_translate("InitBoardUI", "确定"))
        self.lbl_Info.setText(_translate("InitBoardUI", "拖动图标放置于下表中以初始化棋盘..."))
from main import ImgLabel
